### ISSUE TITLE
Habilitar feminino nas versões em português.

### ISSUE THREAD

**Issue by ajandrey** [ppgcc/PP-LaTeX#3]
Versão pt da monografia não apresenta o feminino das palavras "coorientador" e "orientador".

**Comment by olimarborges** [comment]
Olá @ajandrey!
Na verdade você está alterando o nome de uma tag utilizada no arquivo principal do template do LaTeX. As tags programadas no arquivo principal não podem ter seus nomes alterados, por isso está gerando este erro.

Neste caso, você precisa apenas alterar o gênero da orientadora na tag "**\generoori{**\orientadora**}**" (como já está no print enviado) e depois basta inserir o nome da sua orientadora normalmente na tag "**\orientador{**Cláudia da Silva**}**". "\orientador{}" é uma tag apenas.

Qualquer nova questão, só responder por aqui.

Obrigado!
